travis:
  secure:
    BINSTAR_TOKEN: k4/p5H9wrLRMBPoNZgO3mMHWPRamAimWJgtnP5oVEeY2P8L5ZIq++hvzzNdcUYrEQhf+4iDe9y54js6t1CjYHn9C8nEa6WOIyGOtk+7eZnvK9Ups72cBTTeN8419/i47qMkh7ETG+AHCtnTMwImx9a3HtXg8DNbbAGyW6SMrd0gKd9Yz3H83d71Y1mq1phjCN3NcZdSt17CC+SelBRuGGNJujE2eXd4VBI2u0vqdth74Ar3R5qF/ZXCjNa2Ka1qdZMR7MqxTPJPBD4KYbUUvnoYALRdLaEg3jMZYxWzCsvkjsfEPCrJCklC+nbPm9pWLvXbEG/85PV+qZl9PtogVJ3Y1bYl/Kyu0LWTyV1qgXPE2lEH+UmdSzSutTwkvQGSIoQMGAx00oxVgo8NRINcghY0UuhFuoiLQNJxUEux6/Q9a5A+oFuaP5YZFAurmJCqo9IfEU+sk/MImx+RoC65OFvH08NLl2DePN7iAzDzVN5aE/iIBUbhFzI0fTwjtNpJuANdmiH8Ahqj7A0zvhjbSdvG6pCcct2fU0lWmAZNV1l2vSr7GEOXuS3Hy74Y/tMZIU9sxVrHQNXehzLNopfvi7u9U+IoHL6Kp9f1QbQVZMluDYqrjj6O9cibRCA91+/RWRBpLTToHhTpWqmxTrtGpPCir5RFyWohAi7oWoYa/0Xc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
