appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: krGCkOP6yvGT1BeBNPZB1s1eMf+3WB1ZdIQvSmIkoNWj+eO50rJk9xbM9Jhm7X/r0/tFXX5Y6+9/SDzdjAtDetbBG4CM+ooX2Od75/Dd2YojjlSJw7wNEmE6ML7t6+IXtFmmFlDLCwzPUrOMIdBHs2bgVJpCESiCjNzsthopFoGNt0xQmZz62JqnSWJlvxGedTNXFU9yL19yoiaXRg/RdoAcjorjwcR411FWB4IxnWnsotBUvWIAYkuVLZCQj8bWHG3upgPNWsUt49kCjsQpLX6+U5JLqw9/sPXoYvaiOvOUIq/l7CYshFf18S86Z3Ycs5Z4c89iwjM3HeVOWRIPWJ8ypZOxlZM/DWDqHYhIDo+KuZZh4rylgNr5kCYWBlC/ywsdi1Q/LunZNuBdQbL4Z0uZ9ibWmNhyPEI5BQqVfFgxmSgvvPXu8knV5xnTLmjHDC5cbAOF6nhcvjNFX9cOrYIGmrHybt3RtY6YaZY6AcUJ5gMHzVdW+8t3Qbl+zKHNmIooX6QwnFP15KyAzNgIW6BBDOySLruKeguCikZFm6BGdq8HnI5tpFzcWO8y58aqT+iXpt9jZV/uBd2dUztm1N4aqXHPHJhx0Ufdi6g2aBNWmxv+pI+TWqGZd78i29fISiWUumRYGjaI7iQYA6unZebRutRrHzDFRreod9+hIn0=}
