travis:
  secure:
    BINSTAR_TOKEN: P2remWqv1p6uaYobp2AYUXYdMZ3FMjt8TJqrSMCq7rYkspfJQnKGQwU0X0TSKlA0GMDii5Mo2w5zhjprd0JFBMUCjqjSK8KdOwqAA7KS7cD37jZzglo5ddl15qLGJlvOVY5xrB3vdhGsffUleQRoHwx5k4HqcuMO3GD5ahJbM4PWg1Ndq9tfQhSDepJNbnNIaz5cUcEwC1UHGoPATDtHMfW73LE1Iykch/sCCXm7m8y/q/to+8SSUCneuwnkCE+t0e/+lWQZqm8H4zF689irRaFHpAswPfWscU2E2YlmXp+uRpAvQyCv6TvQPikX/NZDmJRWnQqcymbihBa9Rf21tCW3m5Au4UDtdfKhcjoN9f2CG+9/iBLrya7sp0kLVQVnbMv7qWUhWW56vuX+6gUXqrmmER/BKlQu5n9DNyCDgitFy0j3oRD3g59RPJFoK8G5Xwbd98xUYFL1N0Jy6rldO1qgorCSGk2cq7w1XcRZY7Z3fJTuh8RQ3CMQdKEUPZJSU/igC0gy1lnhgqgrmLwRozDi6VNNDhWUtEsQCn1dwFmPgULq/Q/VDptQAxp6RWU5d+gwMW0FSBPlpzahy+dxerRHABXTuEWPcJoQlnDq/mZX6/i/py4+R86cHkrBcf5wMTXg5M4N9HuafyHFNDJT3XBNdBpYja8LRXdY90P6sSg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
